
server:
  port: 80



spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
    template-loader-path: classpath:/templates


debug: false
